wordpress:
  image: wordpress:4
  ports:
    - "8080:80"
  links:
    - mysql
  environment:
    - WORDPRESS_DB_HOST=mysql:3306
    - WORDPRESS_DB_USER=wordpress
    - WORDPRESS_DB_PASSWORD=wordpress
    - WORDPRESS_DB_NAME=wordpress

data:
  image: mysql:5
  volumes:
    - /var/lib/mysql
  command: "true"

mysql:
  restart: always
  image: mysql:5
  volumes_from:
    - data
  ports:
    - "3306:3306"
  environment:
    - MYSQL_DATABASE=wordpress
    - MYSQL_USER=wordpress
    - MYSQL_PASSWORD=wordpress
    - MYSQL_ROOT_PASSWORD=password
